### ISSUE TITLE
Safari doesn't like 'const' in strict mode

### ISSUE THREAD

**Issue by stewartoallen** [qcsimulator/qcsimulator#10]
the page doesn't load correctly and the developer console yields:

bundle.js:38 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

chrome, however, is totally happy

**Comment by wybiral** [comment]
Thanks, I thought there might be some compatibility issues with using ES6 syntax here. Looks like Safari got me. I've added babel to the build process as a fix for now.

https://github.com/wybiral/quantum/commit/9865ae5e18d1fc8ec6d2e85e9f5006734e3ee37f
